package com.jackpan.stockcomputer.model

data class StockEpsListData(
    var EPS: String = "",
    var EPSIOD: String = "",
    var ROA: String = "",
    var ROAIOD: String = "",
    var ROE: String = "",
    var ROEIOD: String = "",
    var number: String = "",
    var name: String = "",
    var deal: String = "",
    var rank: String = "",
    var grossprofit: String = "",
    var grossprofitbillion: String = "",
    var grossprofitgrowing: String = "",
    var grossprofitIOD: String = "",
    var netincome: String = "",
    var netincomebillion: String = "",
    var netincomeIOD: String = "",
    var revenuegrowing: String = "",
    var financialyear: String = "",
    var financialscore: String = ""
/** "EPS" : "183",
"EPSIOD" : "-27.8",
"ROA" : "15.1",
"ROAIOD" : "-4.64",
"ROE" : "18.4",
"ROEIOD" : "-5.79",
"代號" : "3008",
"名稱" : "大立光",
"成交" : "3090",
"排名" : "1",
"毛利(%)" : "67",
"毛利(億)" : "375",
"毛利成長(%)" : "-10.7",
"毛率增減" : "-2.06",
"淨利(%)" : "43.8",
"淨利(億)" : "245",
"淨利成長(%)" : "-13.2",
"淨率增減" : "-2.67",
"營收(億)" : "559",
"營收成長(%)" : "-7.9",
"財報年度" : "2020",
"財報評分" : "85" **/
)